### ISSUE TITLE
Question - How to remove connection in UI

### ISSUE THREAD

**Issue by james-baber** [leon-thomm/Ryven#117]
Hi, might be a silly question, but I can't seem to figure out how to disconnect nodes in the graph without deleting one or the other... There might be a hot-key or something I am missing, but this is what I would like to be able to do
![disconnect-example](https://user-images.githubusercontent.com/67345633/177657549-50e3b9ac-2e06-4891-9cdc-bf30e4186278.gif)
This is Blender btw, but I would like to know how to do this in  the ryven editor

Is this possible? Thanks
Awesome work on this project btw

**Comment by jli113** [comment]
Redo the link can remove the link.

**Comment by kevinlinxc** [comment]
Could we have a simpler way to remove the connection? For example, right click + drag to delete connections that you drag over.
