### ISSUE TITLE
Better way to remove connection?

### ISSUE THREAD

**Issue by kevinlinxc** [leon-thomm/Ryven#128]
From what I can tell, the only way to remove a connection is to remake the connection. I think a more intuitive and faster way to remove links would be to right click + drag over  connections that we don't want. Can this be added?

**Comment by kevinlinxc** [comment]
I know right click is pan right now, but I think spacebar + left click drag or mousewheel click drag would be a good replacement for that as these are used in other programs.

**Comment by leon-thomm** [comment]
> Can this be added?

Not trivial if you consider the cubic paths, but probably doable.

Mouse wheel is kinda bad for touchpad devices.

**Comment by leon-thomm** [comment]
closed in https://github.com/leon-thomm/Ryven/releases/tag/v3.5.0
