### ISSUE TITLE
Is it possible to officially upgrade to Qt6 & PySide6?

### ISSUE THREAD

**Issue by Oxygen-Chu** [leon-thomm/Ryven#138]
I see the App is developed by Qt5 & PySide2, I tried to upgrade to Qt6 & PySide6, but failed.
Is it possible to officially upgrade to Qt6 & PySide6?

**Comment by leon-thomm** [comment]
Ryven uses QtPy as wrapper to seamlessly switch between APIs. QtPy meanwhile has PySide6 support, you can call Ryven from python with `ryven.run_ryven(qt_api='pyside6')`, tough it won't work yet as PySide6 changes some imports etc. but it might be easy to add those changes to the code.

**Comment by leon-thomm** [comment]
closed in https://github.com/leon-thomm/Ryven/releases/tag/v3.5.0

you can now use Python 3.11 with PySide6<6.7 `pip install 'pyside6<6.7'`

note that the default is still PySide2, just run `ryven -q pyside6`
