### ISSUE TITLE
matrices not fully displaying

### ISSUE THREAD

**Issue by GrimPixel** [leon-thomm/Ryven#148]
I tried the matrices example. None of the themes is able to show all the values, lines and checkboxes clearly.

**Comment by leon-thomm** [comment]
Please provide screenshots, it should all fit in the widget. Sometimes exotic screen resolutions can cause problems in the calculation of the space needed to display the matrix, but it should generally adapt appropriately to higher resolutions. In any case it doesn't have anything to do with the themes.

**Comment by GrimPixel** [comment]
I thought there should be texts other than their names. There is no text originally at all.
