### ISSUE TITLE
Put text node open cv

### ISSUE THREAD

**Issue by nenadvkc** [leon-thomm/Ryven#15]
HI, such a nice concept of visual programming I am a beginner and this is a great tool for me, so I tried Put Text node from OpenCV and can't get it to work could you help me maybe I am doing something wrong :|

**Comment by leon-thomm** [comment]
I took a look and have to admit that the put text node doesn't work yet! (so, you did nothing wrong!)
Most of these OpenCV nodes were created by someone else, and although I revised their implementation, I could not fix this one yet (along with a few others). I added that info to its description for the next release. I will probably work on providing a fully working Put Text node in the future but right now, I have to focus on a few other things, sorry!
As long as you use the nodes as shown in the examples project, all nodes with a working implementation should work.

**Comment by leon-thomm** [comment]
fixed in 95775432976ba5f267dbb9c797e0ec82cc6329a3
