### ISSUE TITLE
Runtime update of a node with choices ?

### ISSUE THREAD

**Issue by ArEnSc** [leon-thomm/Ryven#151]
Hey there is a choice field when designing a node, how do you update that node with new values at runtime? It seems to only really work in init. It doesn't update anywhere else sadly especially in the update function

**Comment by leon-thomm** [comment]
I'm not sure what you mean, please provide an example with code.

**Comment by ArEnSc** [comment]
heads up I decided to use something else, there are too many issues with this to be a usable framework, however it helped me understand the space  a lot more and was an awesome learning experience
