### ISSUE TITLE
No such file or directory: 'resources/stylesheets/dark.txt'

### ISSUE THREAD

**Issue by syzkillall** [leon-thomm/Ryven#19]
I use macbook to open this application
however, it throw out error.
<img width="805" alt="截屏2020-08-25 下午12 18 25" src="https://user-images.githubusercontent.com/7632463/91122503-15675880-e6cd-11ea-813f-77128b7edc76.png">

**Comment by NatKTh** [comment]
I think that this may be missed file in stylesheet folder. 

This folder should be include




    On Tuesday, August 25, 2020, 11:18:55 AM GMT+7, syzkillall <notifications@github.com> wrote:  
 
 


I use macbook to open this application
however, it throw out error.

**Comment by leon-thomm** [comment]
_does_ the file exist? it should be [this one](https://github.com/leon-thomm/Ryven/blob/master/Ryven_NodeManager/resources/stylesheets/dark.txt).

**Comment by LukasLoeffler** [comment]
It exists.
After i changed the path it worked fine.
Which operating system are you developing/testing with?

**Comment by leon-thomm** [comment]
After you changed which path? In the Ryven folder there is the resources folder containing the stylesheets. All paths used by Ryven are relative, so as long as you don't move any folders, you should be fine on any OS. If not: which version do you use?
I test on Windows and I'm going to close this soon, since no further info to solve this has been provided.

**Comment by LukasLoeffler** [comment]
I just extracted the zip from your website and did not move any folders.

StartupDialog.py > Line 73 leads to following error: `FileNotFoundError: [Errno 2] No such file or directory: '/resources/stylesheets/dark.txt'`

If I change `f = open('/resources/stylesheets/'+ss+'.txt')` to `f = open('Ryven/resources/stylesheets/'+ss+'.txt')` the application starts properly.

**Comment by leon-thomm** [comment]
Thanks. And you use MacOS?
This is strange because python initializes the StartupDialog in Ryven.py which is already inside the ryven folder.

**Comment by LukasLoeffler** [comment]
I also work on Windows.

**Comment by leon-thomm** [comment]
? it works on my windows 10 without a problem, and all other windows PCs I tried so far, I just tried again with the last version from the website.How did you start Ryven? Did you start it from the console?

**Comment by LukasLoeffler** [comment]
Exactly. I also can replicate.
If I cd into the Ryven folder and execute from there theres no problem.
But if I execute by the whole path it does not find the file.

**Comment by leon-thomm** [comment]
Alright. Could you just replace your Ryven.py with [this one ](https://github.com/leon-thomm/Ryven/blob/master/Ryven/Ryven.py)and try again, please? It should work now from any working dir.

**Comment by LukasLoeffler** [comment]
Successfully tested both execution variants. No issues anymore.

**Comment by leon-thomm** [comment]
nice! thanks for your help!
