### ISSUE TITLE
Crash, when module is not found

### ISSUE THREAD

**Issue by ValdemarQ** [leon-thomm/Ryven#28]
Tried importing module Linalg, had no modules numpy, scipy installed, so software crashed.

**Comment by leon-thomm** [comment]
I'm no sure what you mean, did you install scipy _and_ numpy?

**Comment by ValdemarQ** [comment]
> I'm no sure what you mean, did you install scipy _and_ numpy?
> In order to import a module you must have all required libraries installed. If that's not the case, in the current version the editor will terminate. I agree that this isn't convenient at all, sorry, so that's something I will try to change in the future.

If you try to import package, and have no module installed, you get an error and program crashes without saving. Bascially I tried to import one of the packages Linalg, but it needs extra modules to work such as numpy, scipy, thus if they are not on pc, you get an error and program crashes.

**Comment by leon-thomm** [comment]
yeah, that's what I meant. And I know, this is kinda stupid. Because of those things, you should save your projects quite frequently. I'll try to change the behaviour in this case for a future release.

**Comment by ValdemarQ** [comment]
> yeah, that's what I meant. And I know, this is kinda stupid. Because of those things, you should save your projects quite frequently. I'll try to change the behaviour in this case for a future release.

Sure, no rush, just reported an issue. Maybe consider about doing something like autosave automatically for backups etc...

**Comment by leon-thomm** [comment]
fixed in 2.4.2
