### ISSUE TITLE
Feature request: node groups

### ISSUE THREAD

**Issue by trondarild** [leon-thomm/Ryven#35]
This might be for the long term, but allowing packaging of node graphs together into new nodes (ie node module hierarchies) would allow full scale development and efficient management of graph complexity, as well as re-use of node graphs.

Thanks!

**Comment by leon-thomm** [comment]
#50

**Comment by leon-thomm** [comment]
In [Ryven 3](https://github.com/leon-thomm/Ryven/releases/tag/v3.0.0-alpha) there now exist *macros* for that, see [README](https://github.com/leon-thomm/Ryven#macros--subgraphs)
