### ISSUE TITLE
Workaround suggestion for macos response problems

### ISSUE THREAD

**Issue by trondarild** [leon-thomm/Ryven#37]
Ryven and NodeManager do not respond to mouseclicks out of the box on MacOs. A workaround is to change
the appstyle to "Fusion" instead of the default mac style:
```
 app = QApplication(sys.argv)
 app.setStyle('Fusion')
 sw = StartupDialog()
```
I suggest that Fusion becomes the default mode for mac, or that information about this workaround is added to the Readme.md file.

Thanks!

**Comment by leon-thomm** [comment]
hey, could you try again with Ryven 3 and see if the issue is remaining with?

**Comment by trondarild** [comment]
Works fine now, thanks!

Also congratulation with the new version, I'm particularly excited about the macro-feature!
