### ISSUE TITLE
Only first script is saved in a project

### ISSUE THREAD

**Issue by trondarild** [leon-thomm/Ryven#38]
When saving a project with two scripts, only the first script appears on reload.

Thanks!

**Comment by leon-thomm** [comment]
Did you use the latest release or the master branch? And could you attach your .rpc project file? Thanks^^

**Comment by trondarild** [comment]
I used the master branch. 
Here is a zip with a very simple project, containing two scripts, each only containing a single "val" node.
Hope it helps!
Cheers!
[twoscripts.rpo.zip](https://github.com/leon-thomm/Ryven/files/5875663/twoscripts.rpo.zip)

**Comment by leon-thomm** [comment]
weird that I didn't run into this. Sorry, the master branch probably isn't very safe right now, that will change in the future.
Anyway, should be fixed now (only updated [MainWindow.py](https://github.com/leon-thomm/Ryven/blob/master/Ryven/custom_src/MainWindow.py)) :)

**Comment by trondarild** [comment]
Perfect, thanks for quick response!
