### ISSUE TITLE
Scaling / high res support

### ISSUE THREAD

**Issue by Fylipp** [leon-thomm/Ryven#39]
There are some issues on high resolution displays like below. Is there any way to enable/fix scaling? I found these issues in Ryven 2.4.2 on a 15" 4K screen (X1 Extreme).
 
![image](https://user-images.githubusercontent.com/6892681/106478404-74fe3700-64a9-11eb-8687-d8a989dbbd6c.png)

![image](https://user-images.githubusercontent.com/6892681/106478136-35374f80-64a9-11eb-9cdc-db07bb297435.png)

**Comment by leon-thomm** [comment]
Ah yes, I've had these issues too. I am using a few pixel based sizes internally, which messes up the layouts on higher res screens, which I can probably convert to absolute/DPI dependent scale. 
Some parts might get difficult, for example the node title is already point sized, but the spacing in the layout doesn't seem correct (and these QGraphicsLayouts are a pure nightmare, I hate them so much, I wouldn't be surprised if this gets really ugly). But I'd like to provide support for any resolutions in general. I only have a full HD screen to test right now, and there's too much stuff in the pipeline currently, but I will try some fixing during the next weeks.

**Comment by sphh** [comment]
This PR https://github.com/leon-thomm/ryvencore-qt/pull/21 should solve it.

**Comment by leon-thomm** [comment]
Indeed, thank you!
