### ISSUE TITLE
Feature request: node instance names

### ISSUE THREAD

**Issue by trondarild** [leon-thomm/Ryven#42]
In the context of simulation use cases where different instances of a node represent different parts of a simulated system, It would be useful to be able to explicitly name instances (e.g. when simulating brain networks, node instances correspond to anatomical areas in the brain).

Thanks!

**Comment by leon-thomm** [comment]
renaming instances of the *same* node? Wasn't on my list so far, but I see that this could be quite useful, especially for more sophisticated nodes. using the new system, this should be quite possible. Thanks, I'll try to add that!

**Comment by leon-thomm** [comment]
Added in [Ryven 3](https://github.com/leon-thomm/Ryven/releases/tag/v3.0.0-alpha)
you were right, this is super useful
