### ISSUE TITLE
i found a little two bugs in the last release.

### ISSUE THREAD

**Issue by asgore-undertale** [leon-thomm/Ryven#43]
_i am using windows 7_

**the first one:**
when i move a node in the window do not clear in a right way.
this is a photo:
![1442-06-25 16_52_22-Ryven](https://user-images.githubusercontent.com/52295461/107148700-b38e6880-6965-11eb-8e38-b103bf837a8f.png)

**and this is the second bug:**
(this pixely looking because converting the video to gif)
![bandicam 2021-02-07 17-26-31-106](https://user-images.githubusercontent.com/52295461/107149533-239eed80-696a-11eb-9e28-05bd1b05b580.gif)

and a little suggestion:
for the (+) node and the others, it will be better to make their interaction boxes a little bigger.
and thanks for making this tool, it's amazing.

**Comment by leon-thomm** [comment]
Thanks
- The first thing is actually intended. While you are moving a node in *fast* mode it doesn't rerender the whole scene which causes these artifacs (you can change the mode to *pretty* via *View*->*performance mode*, then it disappears). It just really speeds up the rendering. If I find an equally performant workaround, I'll change it.
- Background drawing: Yes, I couldn't find out how to explicitly force a *background* redraw of the QGraphicsScene. If somebody knows, please respond!
- The size of the hitbox of the nodes is very closely related to the whole GUI, so expanding it further than what is drawn could cause quite messy code I think

**Comment by asgore-undertale** [comment]
thanks man

**Comment by leon-thomm** [comment]
#71
