### ISSUE TITLE
"Times" node: change multiplication operation

### ISSUE THREAD

**Issue by trondarild** [leon-thomm/Ryven#45]
Line 27: Currently a "*=" operation is used; this should be changed to:
sum_val = sum_val * self.input(i)
otherwise the value accumulates and value may propagate backwards to the first input node (e.g. when using numpy arrays as input instead of single values).

Thanks!

**Comment by trondarild** [comment]
It appears that the issue is that "*=" (and +=, -= etc) changes the original structure rather than produce a new one (does not happen with single ints or floats since they are immutable). Here is some more info: 
[Why does += behave unexpectedly on lists?](https://stackoverflow.com/questions/2347265/why-does-behave-unexpectedly-on-lists?noredirect=1&lq=1)

In the example, try repeatedly changing the scalar value; the result should grow.

Cheers!

[mult-example.rpo.zip](https://github.com/leon-thomm/Ryven/files/5994739/mult-example.rpo.zip)

**Comment by leon-thomm** [comment]
should be fixed now, see 1f47d493bbef63c9a6470eebbe8a0b7facec303a
