### ISSUE TITLE
broken import nodes in NodeManager on Linux

### ISSUE THREAD

**Issue by LukasWuehr** [leon-thomm/Ryven#57]
When workin in NodeManager and trying to import Nodes no File Dialog is shown.

I was able to narrow it down to the [filter argument](https://github.com/leon-thomm/Ryven/blob/master/Ryven_NodeManager/MainWindow.py#L188) of MainWindow.py:getOpenFileName. This causes the failure.

Hotfix:
change last argument to 'Ryven Packages(*.rpc)'

Somehow there are no such problems on windows

**System, version**
 - OS: [Manjaro, Ubuntu]

**Comment by leon-thomm** [comment]
Thanks for finding out!
From now on, i.e. in [Ryven 3](#61), there does not exist such thing as a NodeManager anymore, the whole nodes system is very different now.
