### ISSUE TITLE
How to run very simple example ?

### ISSUE THREAD

**Issue by paulz1** [leon-thomm/Ryven#60]
**Description**
I'm very sorry for stupid question. I found your software absolutely fantastic as idea.
But actually  I just could not run it.

Once the flow is created, how to run it?

I created a very simple flow : basically the copy of one of example.
But, once finished, it do nothing. There is no execution, no output.

I could imagine that there is some button, to Run the flow, but in your documentation I didn't see anything like this.

I attach a small screenshot of my flow.

If applicable, add screenshots to help explain the problem.
I understand that the question is silly, probably I just don't understand some basic concept. I tried to find some very simpole step-by-step example it in the project documentation, but without success.

**System, version**
 - OS: Fedora 33, python 3.9.4, PySide2==5.15.2
 - Version: 2.4.2
 

![test_ryven](https://user-images.githubusercontent.com/6814620/120217425-9cd39080-c238-11eb-9f7a-b499fed55479.png)

**Comment by leon-thomm** [comment]
Hey, no worries :) Yes, you want to trigger an execution signal in you for loop node to activate it. You can either right click on the node and click on *exec input 0* or connect a button node to the input and click the button
