### ISSUE TITLE
The exec node output of a std button connected variable input, not other exec input

### ISSUE THREAD

**Issue by KudoLayton** [leon-thomm/Ryven#67]
I remember that exec node output of an std button could be connected to other exec input in the 2.X version.
However, in this 3.0.0-alpha, it doesn't work.

Is there any workaround or plan for fixing it?
![image](https://user-images.githubusercontent.com/12622499/121782246-8e478a80-cbe3-11eb-9da2-00a6d5349689.png)

**Comment by leon-thomm** [comment]
oops, I changed the signature of them and for some reason didn't find these usages in the std nodes package, fixed it in the commit above so it should work now on the master branch

**Comment by KudoLayton** [comment]
It works!
Thank you
