### ISSUE TITLE
Feature request: add Delete as trigger for deletion of nodes

### ISSUE THREAD

**Issue by jo-te** [leon-thomm/Ryven#69]
I don't know if I'm missing something, but it would be really helpful, to delete placed nodes. Since no related command is listed in the command list, I assume this is not possible at the moment.

**Comment by jo-te** [comment]
ah it happens via backspace (on Mac with fn and Delete) This is in my opinion a bit unintuitive, maybe you can support also the Delete key directly, or add an option to the context menu when right-clicking on a node.

**Comment by leon-thomm** [comment]
it is set on the delete key, see [FlowView](https://github.com/leon-thomm/ryvencore-qt/edit/main/ryvencore_qt/src/FlowView.py) line 411. Strange, I don't think anybody else had this issue, so it might be something with your layout...

**Comment by jo-te** [comment]
Could be the problem! I think the issue can be closed in this case. :)
