### ISSUE TITLE
MacOsX 10.13.6: Gui buttons can't be clicked

### ISSUE THREAD

**Issue by trondarild** [leon-thomm/Ryven#7]
Using python 3.6 and 3.8 under OsX 10.13.6, gui starts, but nothing happens if buttons are clicked in either Ryven.py (trying to click on "new project" or "load project") or the nodemanager (trying to click on "add new", "import nodes", "save")

Thank you!

**Comment by leon-thomm** [comment]
Hm, weird. What version of PySide2 do you have installed? Does the output window show any error?

**Comment by trondarild** [comment]
For python3.8 I got pyside2-5.11.2 from pip. However, there appears to be issues with p3.8 and pyside2. I now tried python3.7 on an other machine running osx10.11 and it appears to work. I will try again with p3.7 on the original test machine later and put the result here.

Thank you also for making Ryven, I think it has a lot of potential!

**Comment by leon-thomm** [comment]
Yep, there is a compatibility issue of the Qt bindings when using Python 3.8 with 'older' PySide2 versions, I also discovered that a couple of weeks ago. When using Python 3.8+, please update/reinstall PySide2 with pip to 5.15+, this is what worked for me.
And thanks for the kind words, really appreciate it!

**Comment by trondarild** [comment]
Tried now on osx10.13.6 with p3.7, and still same problem.
Get following print out on cmd line:

Python[54586:36409527] ApplePersistenceIgnoreState: Existing state will not be touched. New state will be written to (null)

**Comment by leon-thomm** [comment]
Which version of PySide2?

**Comment by trondarild** [comment]
Sorry, its pyside2-5.15.0 shiboken2-5.15.0

**Comment by leon-thomm** [comment]
Then you shouldn't have version issues, pyside2-5.15 works for me on 3.6 even. Seems like OSX's _application resume_ feature is interfering with pyside2. Please try to run:
`defaults write org.python.python ApplePersistenceIgnoreState NO` to disable it.
[This](https://stackoverflow.com/questions/18733965/annoying-message-when-opening-windows-from-python-on-os-x-10-8) may help

**Comment by trondarild** [comment]
Still no luck, but thanks. Since this is likely a Qt problem, I will close the issue, however.

**Comment by leon-thomm** [comment]
you could probably get help in the [Qt for Python forum](https://forum.qt.io/category/58/qt-for-python) they usually answer to that kind of stuff
