### ISSUE TITLE
TypeError: can only concatenate str (not "NoneType") to str.

### ISSUE THREAD

**Issue by Hao-Lan** [leon-thomm/Ryven#87]
https://stackoverflow.com/questions/70619058/why-comes-error-when-set-a-attribute-to-a-cls-type-in-ryven

I do not know,it is a buge about Ryven or about python.

Could anyone get it?

**Comment by leon-thomm** [comment]
thanks for reporting. interesting, I only get this on Python 3.10

**Comment by Hao-Lan** [comment]
Me too. python 3.10.x

**Comment by leon-thomm** [comment]
![Screenshot_20220107_111653](https://user-images.githubusercontent.com/29960068/148529287-f84eadbc-14f5-40b1-a6c3-03ab6c25c6aa.png)

...

**Comment by leon-thomm** [comment]
nope, no concurrency at all

**Comment by leon-thomm** [comment]
Looks like it's a PySide2/Shiboken2 thing. The most recent PySide2 version 5.15.2 is not available for Python 3.10, see [here](https://pypi.org/project/PySide2/). Instead, on Python 3.10 it installs version 5.13.2. but I couldn't pin it down to a specific procedure causing the bug on 5.13.2.

Nevertheless, QtPy just got PySide6 support in v2.0.0, and if I run Ryven with PySide6 via QtPy instead (and fix the various new bugs that PySide6 introduces), it does work with Python 3.10.

For now, if you want to use Ryven please go with Python 3.9. There are important bugs in PySide2 which are 5+ years old and don't get fixed, so I wouldn't expect anything soon. Once PySide6 is stable I think I will switch to it, then it should also run on Python 3.10

**Comment by Hao-Lan** [comment]
Thanks!

**Comment by leon-thomm** [comment]
excluded Python 3.10 in release 3.1.1 from #88

**Comment by leon-thomm** [comment]
I am running into this again with Python 3.11, but 3.10 now works. Whenever PySide2 falls back to versions 5.13.* or 5.12.* I am running into this bug, so always make sure Ryven runs on PySide 5.15+
