### ISSUE TITLE
Unable to install ryven (could be me and poetry)

### ISSUE THREAD

**Issue by AJP4** [leon-thomm/Ryven#89]
Hi - I have a virtual environment based on python 3.8, and I am using poetry to help me install packages.  I get the following error message when I try to add ryven.

'[SolverProblemError]
The current project's Python requirement (^3.8) is not compatible with some of the required packages Python requirement:
  - ryven requires Python !=3.10,>=3.6

Because ryven (3.1.1) requires Python !=3.10,>=3.6 and no versions of ryven match >3.1.1,<4.0.0, ryven is forbidden.
So, because project-701-ryven depends on ryven (^3.1.1), version solving failed.'

![Capture](https://user-images.githubusercontent.com/7826593/149549995-689ea89d-54dd-4e30-83d6-94eb2d5229dc.PNG)

I have searched google for equivalent issues, but nothing specific to my problem.  The message suggests I have my version correct so that it might be a poetry issue.  Feel free to close if this issue is not considered ryven driven.

**Comment by leon-thomm** [comment]
hm, looks kinda like [this](https://github.com/python-poetry/poetry/issues/1413). I don't know, I can't spot anything wrong with the version requirements there...

**Comment by AJP4** [comment]
Thank you.  I clearly have a different version of google than you :) .  I have made a change to poetry toml file (changed a ^ to a ~).  Job done.

**Comment by leon-thomm** [comment]
glad I could help xD
