### ISSUE TITLE
Website is not private

### ISSUE THREAD

**Issue by caxelrud** [leon-thomm/Ryven#93]
When trying to access the website, I get the following message:
**Your connection is not private
Attackers might be trying to steal your information from ryven.org (for example, passwords, messages, or credit cards). [Learn more](chrome-error://chromewebdata/#)
NET::ERR_CERT_DATE_INVALID**

**Comment by leon-thomm** [comment]
ah yes, my server didn't reload the SSL certificate, it should work again now
